# Generated by Django 3.2.1 on 2021-06-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gms_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_subjects',
            name='class_id',
        ),
    ]
