# Generated by Django 3.2.1 on 2021-07-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gms_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='gradelevel_id',
        ),
    ]
