# Generated by Django 3.2.1 on 2021-08-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gms_admin', '0002_remove_subjects_gradelevel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('section_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gms_admin.section_subjects')),
            ],
        ),
    ]
